using NCalc;
using Tavernkeep.Core.Entities.Encounters.Participants;

namespace Tavernkeep.Core.Entities.Pathfinder.Conditions
{
	public class CreatureConditionRecord : ConditionRecord
	{
		/* We must to explicitly declare CreatureEncounterParticipant as a property in CreatureConditionRecord.
		 * Otherwise shadow key that will be generated by EF will behave incorrectly
		 * and instead of deleting the CreatureConditionRecord from DB it will simply set 
		 * CreatureEncounterParticipantId key to null and leave the record inside DB
		 * leading to equivalent of a memory leak.
		 */
		public required CreatureEncounterParticipant Participant { get; set; }
		public required Creature Creature { get; set; }
		public override int this[ICollection<string> targetNames]
		{
			get
			{
				foreach (var name in targetNames)
				{
					if (Condition.Modifiers.TryGetValue(name, out var modifier))
					{
						var expression = new Expression(modifier.Formula);
						expression.Parameters["target_level"] = Creature.Level;
						expression.Parameters["condition_level"] = Level;

						return Convert.ToInt32(expression.Evaluate());
					}
				}

				return 0;
			}
		}
	}
}
