// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tavernkeep.Infrastructure.Data.Context;

#nullable disable

namespace Tavernkeep.Infrastructure.Data.Migrations
{
    [DbContext(typeof(SessionContext))]
    [Migration("20240810191752_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.1");

            modelBuilder.Entity("Tavernkeep.Core.Entities.Messages.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SenderId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SenderId");

                    b.ToTable("Messages");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Message");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Tavernkeep.Core.Entities.Pathfinder.Character", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Level")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("Characters");
                });

            modelBuilder.Entity("Tavernkeep.Core.Entities.Pathfinder.Conditions.ConditionMetadata", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("HasLevels")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ConditionMetadata");
                });

            modelBuilder.Entity("Tavernkeep.Core.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Expires")
                        .HasColumnType("TEXT");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("Tavernkeep.Core.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ActiveCharacterId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ActiveCharacterId");

                    b.HasIndex("Login")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Tavernkeep.Core.Entities.Messages.RollMessage", b =>
                {
                    b.HasBaseType("Tavernkeep.Core.Entities.Messages.Message");

                    b.Property<string>("Expression")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RollType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.ToTable("Messages");

                    b.HasDiscriminator().HasValue("RollMessage");
                });

            modelBuilder.Entity("Tavernkeep.Core.Entities.Messages.TextMessage", b =>
                {
                    b.HasBaseType("Tavernkeep.Core.Entities.Messages.Message");

                    b.Property<Guid?>("RecipientId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasIndex("RecipientId");

                    b.ToTable("Messages");

                    b.HasDiscriminator().HasValue("TextMessage");
                });

            modelBuilder.Entity("Tavernkeep.Core.Entities.Messages.SkillRollMessage", b =>
                {
                    b.HasBaseType("Tavernkeep.Core.Entities.Messages.RollMessage");

                    b.ToTable("Messages");

                    b.HasDiscriminator().HasValue("SkillRollMessage");
                });

            modelBuilder.Entity("Tavernkeep.Core.Entities.Messages.Message", b =>
                {
                    b.HasOne("Tavernkeep.Core.Entities.User", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("Tavernkeep.Core.Entities.Pathfinder.Character", b =>
                {
                    b.HasOne("Tavernkeep.Core.Entities.User", "Owner")
                        .WithMany("Characters")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("Tavernkeep.Core.Entities.Pathfinder.Conditions.Condition", "Conditions", b1 =>
                        {
                            b1.Property<Guid>("CharacterId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAddOrUpdate()
                                .HasColumnType("INTEGER");

                            b1.Property<bool>("HasLevels")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Level")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.HasKey("CharacterId", "Id");

                            b1.ToTable("Characters");

                            b1.ToJson("Conditions");

                            b1.WithOwner()
                                .HasForeignKey("CharacterId");

                            b1.OwnsMany("Tavernkeep.Core.Entities.Pathfinder.Modifiers.Modifier", "Modifiers", b2 =>
                                {
                                    b2.Property<Guid>("ConditionCharacterId")
                                        .HasColumnType("TEXT");

                                    b2.Property<int>("ConditionId")
                                        .HasColumnType("INTEGER");

                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAddOrUpdate()
                                        .HasColumnType("INTEGER");

                                    b2.Property<bool>("IsBonus")
                                        .HasColumnType("INTEGER");

                                    b2.Property<int>("Scaling")
                                        .HasColumnType("INTEGER");

                                    b2.Property<string>("Targets")
                                        .IsRequired()
                                        .HasColumnType("TEXT");

                                    b2.Property<int>("Type")
                                        .HasColumnType("INTEGER");

                                    b2.Property<int>("Value")
                                        .HasColumnType("INTEGER");

                                    b2.HasKey("ConditionCharacterId", "ConditionId", "Id");

                                    b2.ToTable("Characters");

                                    b2.ToJson("Modifiers");

                                    b2.WithOwner()
                                        .HasForeignKey("ConditionCharacterId", "ConditionId");
                                });

                            b1.Navigation("Modifiers");
                        });

                    b.OwnsOne("Tavernkeep.Core.Entities.Pathfinder.Health", "Health", b1 =>
                        {
                            b1.Property<Guid>("CharacterId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("Current")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Max")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Temporary")
                                .HasColumnType("INTEGER");

                            b1.HasKey("CharacterId");

                            b1.ToTable("Characters");

                            b1.ToJson("Health");

                            b1.WithOwner()
                                .HasForeignKey("CharacterId");
                        });

                    b.OwnsOne("Tavernkeep.Core.Entities.Pathfinder.ArmorClass", "Armor", b1 =>
                        {
                            b1.Property<Guid>("OwnerId")
                                .HasColumnType("TEXT");

                            b1.HasKey("OwnerId");

                            b1.ToTable("Characters");

                            b1.ToJson("Armor");

                            b1.WithOwner("Owner")
                                .HasForeignKey("OwnerId");

                            b1.OwnsOne("Tavernkeep.Core.Entities.Pathfinder.ArmorProficiencies", "Proficiencies", b2 =>
                                {
                                    b2.Property<Guid>("ArmorClassOwnerId")
                                        .HasColumnType("TEXT");

                                    b2.Property<int>("Heavy")
                                        .HasColumnType("INTEGER");

                                    b2.Property<int>("Light")
                                        .HasColumnType("INTEGER");

                                    b2.Property<int>("Medium")
                                        .HasColumnType("INTEGER");

                                    b2.Property<int>("Unarmored")
                                        .HasColumnType("INTEGER");

                                    b2.HasKey("ArmorClassOwnerId");

                                    b2.ToTable("Characters");

                                    b2.WithOwner()
                                        .HasForeignKey("ArmorClassOwnerId");
                                });

                            b1.Navigation("Owner");

                            b1.Navigation("Proficiencies")
                                .IsRequired();
                        });

                    b.OwnsOne("Tavernkeep.Core.Entities.Pathfinder.Skill", "Acrobatics", b1 =>
                        {
                            b1.Property<Guid>("OwnerId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("BaseAbility")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Proficiency")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Type")
                                .HasColumnType("INTEGER");

                            b1.HasKey("OwnerId");

                            b1.ToTable("Characters");

                            b1.ToJson("Acrobatics");

                            b1.WithOwner("Owner")
                                .HasForeignKey("OwnerId");

                            b1.Navigation("Owner");
                        });

                    b.OwnsOne("Tavernkeep.Core.Entities.Pathfinder.Skill", "Arcana", b1 =>
                        {
                            b1.Property<Guid>("OwnerId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("BaseAbility")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Proficiency")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Type")
                                .HasColumnType("INTEGER");

                            b1.HasKey("OwnerId");

                            b1.ToTable("Characters");

                            b1.ToJson("Arcana");

                            b1.WithOwner("Owner")
                                .HasForeignKey("OwnerId");

                            b1.Navigation("Owner");
                        });

                    b.OwnsOne("Tavernkeep.Core.Entities.Pathfinder.Skill", "Athletics", b1 =>
                        {
                            b1.Property<Guid>("OwnerId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("BaseAbility")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Proficiency")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Type")
                                .HasColumnType("INTEGER");

                            b1.HasKey("OwnerId");

                            b1.ToTable("Characters");

                            b1.ToJson("Athletics");

                            b1.WithOwner("Owner")
                                .HasForeignKey("OwnerId");

                            b1.Navigation("Owner");
                        });

                    b.OwnsOne("Tavernkeep.Core.Entities.Pathfinder.Ability", "Charisma", b1 =>
                        {
                            b1.Property<Guid>("OwnerId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("Score")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Type")
                                .HasColumnType("INTEGER");

                            b1.HasKey("OwnerId");

                            b1.ToTable("Characters");

                            b1.ToJson("Charisma");

                            b1.WithOwner("Owner")
                                .HasForeignKey("OwnerId");

                            b1.Navigation("Owner");
                        });

                    b.OwnsOne("Tavernkeep.Core.Entities.Pathfinder.Ability", "Constitution", b1 =>
                        {
                            b1.Property<Guid>("OwnerId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("Score")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Type")
                                .HasColumnType("INTEGER");

                            b1.HasKey("OwnerId");

                            b1.ToTable("Characters");

                            b1.ToJson("Constitution");

                            b1.WithOwner("Owner")
                                .HasForeignKey("OwnerId");

                            b1.Navigation("Owner");
                        });

                    b.OwnsOne("Tavernkeep.Core.Entities.Pathfinder.Skill", "Crafting", b1 =>
                        {
                            b1.Property<Guid>("OwnerId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("BaseAbility")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Proficiency")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Type")
                                .HasColumnType("INTEGER");

                            b1.HasKey("OwnerId");

                            b1.ToTable("Characters");

                            b1.ToJson("Crafting");

                            b1.WithOwner("Owner")
                                .HasForeignKey("OwnerId");

                            b1.Navigation("Owner");
                        });

                    b.OwnsOne("Tavernkeep.Core.Entities.Pathfinder.Skill", "Deception", b1 =>
                        {
                            b1.Property<Guid>("OwnerId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("BaseAbility")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Proficiency")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Type")
                                .HasColumnType("INTEGER");

                            b1.HasKey("OwnerId");

                            b1.ToTable("Characters");

                            b1.ToJson("Deception");

                            b1.WithOwner("Owner")
                                .HasForeignKey("OwnerId");

                            b1.Navigation("Owner");
                        });

                    b.OwnsOne("Tavernkeep.Core.Entities.Pathfinder.Ability", "Dexterity", b1 =>
                        {
                            b1.Property<Guid>("OwnerId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("Score")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Type")
                                .HasColumnType("INTEGER");

                            b1.HasKey("OwnerId");

                            b1.ToTable("Characters");

                            b1.ToJson("Dexterity");

                            b1.WithOwner("Owner")
                                .HasForeignKey("OwnerId");

                            b1.Navigation("Owner");
                        });

                    b.OwnsOne("Tavernkeep.Core.Entities.Pathfinder.Skill", "Diplomacy", b1 =>
                        {
                            b1.Property<Guid>("OwnerId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("BaseAbility")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Proficiency")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Type")
                                .HasColumnType("INTEGER");

                            b1.HasKey("OwnerId");

                            b1.ToTable("Characters");

                            b1.ToJson("Diplomacy");

                            b1.WithOwner("Owner")
                                .HasForeignKey("OwnerId");

                            b1.Navigation("Owner");
                        });

                    b.OwnsOne("Tavernkeep.Core.Entities.Pathfinder.SavingThrow", "Fortitude", b1 =>
                        {
                            b1.Property<Guid>("OwnerId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("BaseAbility")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Proficiency")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Type")
                                .HasColumnType("INTEGER");

                            b1.HasKey("OwnerId");

                            b1.ToTable("Characters");

                            b1.ToJson("Fortitude");

                            b1.WithOwner("Owner")
                                .HasForeignKey("OwnerId");

                            b1.Navigation("Owner");
                        });

                    b.OwnsOne("Tavernkeep.Core.Entities.Pathfinder.Ability", "Intelligence", b1 =>
                        {
                            b1.Property<Guid>("OwnerId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("Score")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Type")
                                .HasColumnType("INTEGER");

                            b1.HasKey("OwnerId");

                            b1.ToTable("Characters");

                            b1.ToJson("Intelligence");

                            b1.WithOwner("Owner")
                                .HasForeignKey("OwnerId");

                            b1.Navigation("Owner");
                        });

                    b.OwnsOne("Tavernkeep.Core.Entities.Pathfinder.Skill", "Intimidation", b1 =>
                        {
                            b1.Property<Guid>("OwnerId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("BaseAbility")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Proficiency")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Type")
                                .HasColumnType("INTEGER");

                            b1.HasKey("OwnerId");

                            b1.ToTable("Characters");

                            b1.ToJson("Intimidation");

                            b1.WithOwner("Owner")
                                .HasForeignKey("OwnerId");

                            b1.Navigation("Owner");
                        });

                    b.OwnsOne("Tavernkeep.Core.Entities.Pathfinder.Skill", "Medicine", b1 =>
                        {
                            b1.Property<Guid>("OwnerId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("BaseAbility")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Proficiency")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Type")
                                .HasColumnType("INTEGER");

                            b1.HasKey("OwnerId");

                            b1.ToTable("Characters");

                            b1.ToJson("Medicine");

                            b1.WithOwner("Owner")
                                .HasForeignKey("OwnerId");

                            b1.Navigation("Owner");
                        });

                    b.OwnsOne("Tavernkeep.Core.Entities.Pathfinder.Skill", "Nature", b1 =>
                        {
                            b1.Property<Guid>("OwnerId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("BaseAbility")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Proficiency")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Type")
                                .HasColumnType("INTEGER");

                            b1.HasKey("OwnerId");

                            b1.ToTable("Characters");

                            b1.ToJson("Nature");

                            b1.WithOwner("Owner")
                                .HasForeignKey("OwnerId");

                            b1.Navigation("Owner");
                        });

                    b.OwnsOne("Tavernkeep.Core.Entities.Pathfinder.Skill", "Occultism", b1 =>
                        {
                            b1.Property<Guid>("OwnerId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("BaseAbility")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Proficiency")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Type")
                                .HasColumnType("INTEGER");

                            b1.HasKey("OwnerId");

                            b1.ToTable("Characters");

                            b1.ToJson("Occultism");

                            b1.WithOwner("Owner")
                                .HasForeignKey("OwnerId");

                            b1.Navigation("Owner");
                        });

                    b.OwnsOne("Tavernkeep.Core.Entities.Pathfinder.Skill", "Performance", b1 =>
                        {
                            b1.Property<Guid>("OwnerId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("BaseAbility")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Proficiency")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Type")
                                .HasColumnType("INTEGER");

                            b1.HasKey("OwnerId");

                            b1.ToTable("Characters");

                            b1.ToJson("Performance");

                            b1.WithOwner("Owner")
                                .HasForeignKey("OwnerId");

                            b1.Navigation("Owner");
                        });

                    b.OwnsOne("Tavernkeep.Core.Entities.Pathfinder.SavingThrow", "Reflex", b1 =>
                        {
                            b1.Property<Guid>("OwnerId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("BaseAbility")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Proficiency")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Type")
                                .HasColumnType("INTEGER");

                            b1.HasKey("OwnerId");

                            b1.ToTable("Characters");

                            b1.ToJson("Reflex");

                            b1.WithOwner("Owner")
                                .HasForeignKey("OwnerId");

                            b1.Navigation("Owner");
                        });

                    b.OwnsOne("Tavernkeep.Core.Entities.Pathfinder.Skill", "Religion", b1 =>
                        {
                            b1.Property<Guid>("OwnerId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("BaseAbility")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Proficiency")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Type")
                                .HasColumnType("INTEGER");

                            b1.HasKey("OwnerId");

                            b1.ToTable("Characters");

                            b1.ToJson("Religion");

                            b1.WithOwner("Owner")
                                .HasForeignKey("OwnerId");

                            b1.Navigation("Owner");
                        });

                    b.OwnsOne("Tavernkeep.Core.Entities.Pathfinder.Skill", "Society", b1 =>
                        {
                            b1.Property<Guid>("OwnerId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("BaseAbility")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Proficiency")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Type")
                                .HasColumnType("INTEGER");

                            b1.HasKey("OwnerId");

                            b1.ToTable("Characters");

                            b1.ToJson("Society");

                            b1.WithOwner("Owner")
                                .HasForeignKey("OwnerId");

                            b1.Navigation("Owner");
                        });

                    b.OwnsOne("Tavernkeep.Core.Entities.Pathfinder.Skill", "Stealth", b1 =>
                        {
                            b1.Property<Guid>("OwnerId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("BaseAbility")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Proficiency")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Type")
                                .HasColumnType("INTEGER");

                            b1.HasKey("OwnerId");

                            b1.ToTable("Characters");

                            b1.ToJson("Stealth");

                            b1.WithOwner("Owner")
                                .HasForeignKey("OwnerId");

                            b1.Navigation("Owner");
                        });

                    b.OwnsOne("Tavernkeep.Core.Entities.Pathfinder.Ability", "Strength", b1 =>
                        {
                            b1.Property<Guid>("OwnerId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("Score")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Type")
                                .HasColumnType("INTEGER");

                            b1.HasKey("OwnerId");

                            b1.ToTable("Characters");

                            b1.ToJson("Strength");

                            b1.WithOwner("Owner")
                                .HasForeignKey("OwnerId");

                            b1.Navigation("Owner");
                        });

                    b.OwnsOne("Tavernkeep.Core.Entities.Pathfinder.Skill", "Survival", b1 =>
                        {
                            b1.Property<Guid>("OwnerId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("BaseAbility")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Proficiency")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Type")
                                .HasColumnType("INTEGER");

                            b1.HasKey("OwnerId");

                            b1.ToTable("Characters");

                            b1.ToJson("Survival");

                            b1.WithOwner("Owner")
                                .HasForeignKey("OwnerId");

                            b1.Navigation("Owner");
                        });

                    b.OwnsOne("Tavernkeep.Core.Entities.Pathfinder.Skill", "Thievery", b1 =>
                        {
                            b1.Property<Guid>("OwnerId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("BaseAbility")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Proficiency")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Type")
                                .HasColumnType("INTEGER");

                            b1.HasKey("OwnerId");

                            b1.ToTable("Characters");

                            b1.ToJson("Thievery");

                            b1.WithOwner("Owner")
                                .HasForeignKey("OwnerId");

                            b1.Navigation("Owner");
                        });

                    b.OwnsOne("Tavernkeep.Core.Entities.Pathfinder.SavingThrow", "Will", b1 =>
                        {
                            b1.Property<Guid>("OwnerId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("BaseAbility")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Proficiency")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Type")
                                .HasColumnType("INTEGER");

                            b1.HasKey("OwnerId");

                            b1.ToTable("Characters");

                            b1.ToJson("Will");

                            b1.WithOwner("Owner")
                                .HasForeignKey("OwnerId");

                            b1.Navigation("Owner");
                        });

                    b.OwnsOne("Tavernkeep.Core.Entities.Pathfinder.Ability", "Wisdom", b1 =>
                        {
                            b1.Property<Guid>("OwnerId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("Score")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Type")
                                .HasColumnType("INTEGER");

                            b1.HasKey("OwnerId");

                            b1.ToTable("Characters");

                            b1.ToJson("Wisdom");

                            b1.WithOwner("Owner")
                                .HasForeignKey("OwnerId");

                            b1.Navigation("Owner");
                        });

                    b.OwnsMany("Tavernkeep.Core.Entities.Pathfinder.Lore", "Lores", b1 =>
                        {
                            b1.Property<Guid>("OwnerId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Proficiency")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Topic")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.HasKey("OwnerId", "Id");

                            b1.ToTable("Characters");

                            b1.ToJson("Lores");

                            b1.WithOwner("Owner")
                                .HasForeignKey("OwnerId");

                            b1.Navigation("Owner");
                        });

                    b.Navigation("Acrobatics")
                        .IsRequired();

                    b.Navigation("Arcana")
                        .IsRequired();

                    b.Navigation("Armor")
                        .IsRequired();

                    b.Navigation("Athletics")
                        .IsRequired();

                    b.Navigation("Charisma")
                        .IsRequired();

                    b.Navigation("Conditions");

                    b.Navigation("Constitution")
                        .IsRequired();

                    b.Navigation("Crafting")
                        .IsRequired();

                    b.Navigation("Deception")
                        .IsRequired();

                    b.Navigation("Dexterity")
                        .IsRequired();

                    b.Navigation("Diplomacy")
                        .IsRequired();

                    b.Navigation("Fortitude")
                        .IsRequired();

                    b.Navigation("Health")
                        .IsRequired();

                    b.Navigation("Intelligence")
                        .IsRequired();

                    b.Navigation("Intimidation")
                        .IsRequired();

                    b.Navigation("Lores");

                    b.Navigation("Medicine")
                        .IsRequired();

                    b.Navigation("Nature")
                        .IsRequired();

                    b.Navigation("Occultism")
                        .IsRequired();

                    b.Navigation("Owner");

                    b.Navigation("Performance")
                        .IsRequired();

                    b.Navigation("Reflex")
                        .IsRequired();

                    b.Navigation("Religion")
                        .IsRequired();

                    b.Navigation("Society")
                        .IsRequired();

                    b.Navigation("Stealth")
                        .IsRequired();

                    b.Navigation("Strength")
                        .IsRequired();

                    b.Navigation("Survival")
                        .IsRequired();

                    b.Navigation("Thievery")
                        .IsRequired();

                    b.Navigation("Will")
                        .IsRequired();

                    b.Navigation("Wisdom")
                        .IsRequired();
                });

            modelBuilder.Entity("Tavernkeep.Core.Entities.Pathfinder.Conditions.ConditionMetadata", b =>
                {
                    b.OwnsMany("Tavernkeep.Core.Entities.Pathfinder.Modifiers.Modifier", "Modifiers", b1 =>
                        {
                            b1.Property<Guid>("ConditionMetadataId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("INTEGER");

                            b1.Property<bool>("IsBonus")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Scaling")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Targets")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<int>("Type")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Value")
                                .HasColumnType("INTEGER");

                            b1.HasKey("ConditionMetadataId", "Id");

                            b1.ToTable("ConditionMetadata");

                            b1.ToJson("Modifiers");

                            b1.WithOwner()
                                .HasForeignKey("ConditionMetadataId");
                        });

                    b.OwnsMany("Tavernkeep.Core.Entities.Pathfinder.Conditions.Condition", "Related", b1 =>
                        {
                            b1.Property<Guid>("ConditionMetadataId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("INTEGER");

                            b1.Property<bool>("HasLevels")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Level")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.HasKey("ConditionMetadataId", "Id");

                            b1.ToTable("ConditionMetadata");

                            b1.ToJson("Related");

                            b1.WithOwner()
                                .HasForeignKey("ConditionMetadataId");

                            b1.OwnsMany("Tavernkeep.Core.Entities.Pathfinder.Modifiers.Modifier", "Modifiers", b2 =>
                                {
                                    b2.Property<Guid>("ConditionMetadataId")
                                        .HasColumnType("TEXT");

                                    b2.Property<int>("ConditionId")
                                        .HasColumnType("INTEGER");

                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAddOrUpdate()
                                        .HasColumnType("INTEGER");

                                    b2.Property<bool>("IsBonus")
                                        .HasColumnType("INTEGER");

                                    b2.Property<int>("Scaling")
                                        .HasColumnType("INTEGER");

                                    b2.Property<string>("Targets")
                                        .IsRequired()
                                        .HasColumnType("TEXT");

                                    b2.Property<int>("Type")
                                        .HasColumnType("INTEGER");

                                    b2.Property<int>("Value")
                                        .HasColumnType("INTEGER");

                                    b2.HasKey("ConditionMetadataId", "ConditionId", "Id");

                                    b2.ToTable("ConditionMetadata");

                                    b2.ToJson("Modifiers");

                                    b2.WithOwner()
                                        .HasForeignKey("ConditionMetadataId", "ConditionId");
                                });

                            b1.Navigation("Modifiers");
                        });

                    b.Navigation("Modifiers");

                    b.Navigation("Related");
                });

            modelBuilder.Entity("Tavernkeep.Core.Entities.User", b =>
                {
                    b.HasOne("Tavernkeep.Core.Entities.Pathfinder.Character", "ActiveCharacter")
                        .WithMany()
                        .HasForeignKey("ActiveCharacterId");

                    b.Navigation("ActiveCharacter");
                });

            modelBuilder.Entity("Tavernkeep.Core.Entities.Messages.RollMessage", b =>
                {
                    b.OwnsOne("Tavernkeep.Core.Entities.Rolls.RollResult", "Result", b1 =>
                        {
                            b1.Property<Guid>("RollMessageId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("Modifier")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Value")
                                .HasColumnType("INTEGER");

                            b1.HasKey("RollMessageId");

                            b1.ToTable("Messages");

                            b1.ToJson("Result");

                            b1.WithOwner()
                                .HasForeignKey("RollMessageId");

                            b1.OwnsMany("Tavernkeep.Core.Entities.Rolls.ThrowResult", "Results", b2 =>
                                {
                                    b2.Property<Guid>("RollResultRollMessageId")
                                        .HasColumnType("TEXT");

                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAddOrUpdate()
                                        .HasColumnType("INTEGER");

                                    b2.Property<string>("Type")
                                        .IsRequired()
                                        .HasColumnType("TEXT");

                                    b2.Property<int>("Value")
                                        .HasColumnType("INTEGER");

                                    b2.HasKey("RollResultRollMessageId", "Id");

                                    b2.ToTable("Messages");

                                    b2.WithOwner()
                                        .HasForeignKey("RollResultRollMessageId");
                                });

                            b1.Navigation("Results");
                        });

                    b.Navigation("Result")
                        .IsRequired();
                });

            modelBuilder.Entity("Tavernkeep.Core.Entities.Messages.TextMessage", b =>
                {
                    b.HasOne("Tavernkeep.Core.Entities.User", "Recipient")
                        .WithMany()
                        .HasForeignKey("RecipientId");

                    b.Navigation("Recipient");
                });

            modelBuilder.Entity("Tavernkeep.Core.Entities.Messages.SkillRollMessage", b =>
                {
                    b.OwnsOne("Tavernkeep.Core.Entities.Snapshots.SkillSnapshot", "Skill", b1 =>
                        {
                            b1.Property<Guid>("SkillRollMessageId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("Bonus")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Proficiency")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Type")
                                .HasColumnType("INTEGER");

                            b1.HasKey("SkillRollMessageId");

                            b1.ToTable("Messages");

                            b1.ToJson("Skill");

                            b1.WithOwner()
                                .HasForeignKey("SkillRollMessageId");
                        });

                    b.Navigation("Skill")
                        .IsRequired();
                });

            modelBuilder.Entity("Tavernkeep.Core.Entities.User", b =>
                {
                    b.Navigation("Characters");
                });
#pragma warning restore 612, 618
        }
    }
}
