// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tavernkeep.Infrastructure.Data.Context;

#nullable disable

namespace Tavernkeep.Infrastructure.Data.Migrations
{
    [DbContext(typeof(SessionContext))]
    [Migration("20250112165323_SpeedsActiveFlag")]
    partial class SpeedsActiveFlag
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("Tavernkeep.Core.Entities.Messages.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(34)
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SenderId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SenderId");

                    b.ToTable("Messages");

                    b.HasDiscriminator().HasValue("Message");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Tavernkeep.Core.Entities.Pathfinder.Character", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Ancestry")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Class")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("Characters");
                });

            modelBuilder.Entity("Tavernkeep.Core.Entities.Pathfinder.Conditions.ConditionTemplate", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("HasLevels")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.HasKey("Name");

                    b.ToTable("Conditions");
                });

            modelBuilder.Entity("Tavernkeep.Core.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Expires")
                        .HasColumnType("TEXT");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("Tavernkeep.Core.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ActiveCharacterId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ActiveCharacterId");

                    b.HasIndex("Login")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Tavernkeep.Core.Entities.Messages.RollMessage", b =>
                {
                    b.HasBaseType("Tavernkeep.Core.Entities.Messages.Message");

                    b.Property<string>("Expression")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RollType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.ToTable("Messages");

                    b.HasDiscriminator().HasValue("RollMessage");
                });

            modelBuilder.Entity("Tavernkeep.Core.Entities.Messages.TextMessage", b =>
                {
                    b.HasBaseType("Tavernkeep.Core.Entities.Messages.Message");

                    b.Property<Guid?>("RecipientId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasIndex("RecipientId");

                    b.ToTable("Messages");

                    b.HasDiscriminator().HasValue("TextMessage");
                });

            modelBuilder.Entity("Tavernkeep.Core.Entities.Messages.SavingThrowRollMessage", b =>
                {
                    b.HasBaseType("Tavernkeep.Core.Entities.Messages.RollMessage");

                    b.ToTable("Messages");

                    b.HasDiscriminator().HasValue("SavingThrowRollMessage");
                });

            modelBuilder.Entity("Tavernkeep.Core.Entities.Messages.SkillRollMessage", b =>
                {
                    b.HasBaseType("Tavernkeep.Core.Entities.Messages.RollMessage");

                    b.ToTable("Messages");

                    b.HasDiscriminator().HasValue("SkillRollMessage");
                });

            modelBuilder.Entity("Tavernkeep.Core.Entities.Messages.Message", b =>
                {
                    b.HasOne("Tavernkeep.Core.Entities.User", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("Tavernkeep.Core.Entities.Pathfinder.Character", b =>
                {
                    b.HasOne("Tavernkeep.Core.Entities.User", "Owner")
                        .WithMany("Characters")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("Tavernkeep.Core.Entities.Pathfinder.Conditions.Condition", "Conditions", b1 =>
                        {
                            b1.Property<Guid>("CharacterId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAddOrUpdate()
                                .HasColumnType("INTEGER");

                            b1.Property<bool>("HasLevels")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Level")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.HasKey("CharacterId", "__synthesizedOrdinal");

                            b1.ToTable("Characters");

                            b1.ToJson("Conditions");

                            b1.WithOwner()
                                .HasForeignKey("CharacterId");

                            b1.OwnsMany("Tavernkeep.Core.Entities.Pathfinder.Modifiers.Modifier", "Modifiers", b2 =>
                                {
                                    b2.Property<Guid>("ConditionCharacterId")
                                        .HasColumnType("TEXT");

                                    b2.Property<int>("Condition__synthesizedOrdinal")
                                        .HasColumnType("INTEGER");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAddOrUpdate()
                                        .HasColumnType("INTEGER");

                                    b2.Property<bool>("IsBonus")
                                        .HasColumnType("INTEGER");

                                    b2.Property<int>("Scaling")
                                        .HasColumnType("INTEGER");

                                    b2.PrimitiveCollection<string>("Targets")
                                        .IsRequired()
                                        .HasColumnType("TEXT");

                                    b2.Property<int>("Type")
                                        .HasColumnType("INTEGER");

                                    b2.Property<int>("Value")
                                        .HasColumnType("INTEGER");

                                    b2.HasKey("ConditionCharacterId", "Condition__synthesizedOrdinal", "__synthesizedOrdinal");

                                    b2.ToTable("Characters");

                                    b2.ToJson("Modifiers");

                                    b2.WithOwner()
                                        .HasForeignKey("ConditionCharacterId", "Condition__synthesizedOrdinal");
                                });

                            b1.Navigation("Modifiers");
                        });

                    b.OwnsOne("Tavernkeep.Core.Entities.Pathfinder.Properties.Skill", "Acrobatics", b1 =>
                        {
                            b1.Property<Guid>("OwnerId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("BaseAbility")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Proficiency")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Type")
                                .HasColumnType("INTEGER");

                            b1.HasKey("OwnerId");

                            b1.ToTable("Characters");

                            b1.ToJson("Acrobatics");

                            b1.WithOwner("Owner")
                                .HasForeignKey("OwnerId");

                            b1.Navigation("Owner");
                        });

                    b.OwnsOne("Tavernkeep.Core.Entities.Pathfinder.Properties.Skill", "Arcana", b1 =>
                        {
                            b1.Property<Guid>("OwnerId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("BaseAbility")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Proficiency")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Type")
                                .HasColumnType("INTEGER");

                            b1.HasKey("OwnerId");

                            b1.ToTable("Characters");

                            b1.ToJson("Arcana");

                            b1.WithOwner("Owner")
                                .HasForeignKey("OwnerId");

                            b1.Navigation("Owner");
                        });

                    b.OwnsOne("Tavernkeep.Core.Entities.Pathfinder.Properties.Skill", "Athletics", b1 =>
                        {
                            b1.Property<Guid>("OwnerId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("BaseAbility")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Proficiency")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Type")
                                .HasColumnType("INTEGER");

                            b1.HasKey("OwnerId");

                            b1.ToTable("Characters");

                            b1.ToJson("Athletics");

                            b1.WithOwner("Owner")
                                .HasForeignKey("OwnerId");

                            b1.Navigation("Owner");
                        });

                    b.OwnsOne("Tavernkeep.Core.Entities.Pathfinder.Properties.Speed", "Burrow", b1 =>
                        {
                            b1.Property<Guid>("OwnerId")
                                .HasColumnType("TEXT");

                            b1.Property<bool>("Active")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Base")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Type")
                                .HasColumnType("INTEGER");

                            b1.HasKey("OwnerId");

                            b1.ToTable("Characters");

                            b1.ToJson("Burrow");

                            b1.WithOwner("Owner")
                                .HasForeignKey("OwnerId");

                            b1.Navigation("Owner");
                        });

                    b.OwnsOne("Tavernkeep.Core.Entities.Pathfinder.Properties.Ability", "Charisma", b1 =>
                        {
                            b1.Property<Guid>("OwnerId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("Score")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Type")
                                .HasColumnType("INTEGER");

                            b1.HasKey("OwnerId");

                            b1.ToTable("Characters");

                            b1.ToJson("Charisma");

                            b1.WithOwner("Owner")
                                .HasForeignKey("OwnerId");

                            b1.Navigation("Owner");
                        });

                    b.OwnsOne("Tavernkeep.Core.Entities.Pathfinder.Properties.Speed", "Climb", b1 =>
                        {
                            b1.Property<Guid>("OwnerId")
                                .HasColumnType("TEXT");

                            b1.Property<bool>("Active")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Base")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Type")
                                .HasColumnType("INTEGER");

                            b1.HasKey("OwnerId");

                            b1.ToTable("Characters");

                            b1.ToJson("Climb");

                            b1.WithOwner("Owner")
                                .HasForeignKey("OwnerId");

                            b1.Navigation("Owner");
                        });

                    b.OwnsOne("Tavernkeep.Core.Entities.Pathfinder.Properties.Ability", "Constitution", b1 =>
                        {
                            b1.Property<Guid>("OwnerId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("Score")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Type")
                                .HasColumnType("INTEGER");

                            b1.HasKey("OwnerId");

                            b1.ToTable("Characters");

                            b1.ToJson("Constitution");

                            b1.WithOwner("Owner")
                                .HasForeignKey("OwnerId");

                            b1.Navigation("Owner");
                        });

                    b.OwnsOne("Tavernkeep.Core.Entities.Pathfinder.Properties.Skill", "Crafting", b1 =>
                        {
                            b1.Property<Guid>("OwnerId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("BaseAbility")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Proficiency")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Type")
                                .HasColumnType("INTEGER");

                            b1.HasKey("OwnerId");

                            b1.ToTable("Characters");

                            b1.ToJson("Crafting");

                            b1.WithOwner("Owner")
                                .HasForeignKey("OwnerId");

                            b1.Navigation("Owner");
                        });

                    b.OwnsOne("Tavernkeep.Core.Entities.Pathfinder.Properties.Skill", "Deception", b1 =>
                        {
                            b1.Property<Guid>("OwnerId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("BaseAbility")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Proficiency")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Type")
                                .HasColumnType("INTEGER");

                            b1.HasKey("OwnerId");

                            b1.ToTable("Characters");

                            b1.ToJson("Deception");

                            b1.WithOwner("Owner")
                                .HasForeignKey("OwnerId");

                            b1.Navigation("Owner");
                        });

                    b.OwnsOne("Tavernkeep.Core.Entities.Pathfinder.Properties.Ability", "Dexterity", b1 =>
                        {
                            b1.Property<Guid>("OwnerId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("Score")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Type")
                                .HasColumnType("INTEGER");

                            b1.HasKey("OwnerId");

                            b1.ToTable("Characters");

                            b1.ToJson("Dexterity");

                            b1.WithOwner("Owner")
                                .HasForeignKey("OwnerId");

                            b1.Navigation("Owner");
                        });

                    b.OwnsOne("Tavernkeep.Core.Entities.Pathfinder.Properties.Skill", "Diplomacy", b1 =>
                        {
                            b1.Property<Guid>("OwnerId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("BaseAbility")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Proficiency")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Type")
                                .HasColumnType("INTEGER");

                            b1.HasKey("OwnerId");

                            b1.ToTable("Characters");

                            b1.ToJson("Diplomacy");

                            b1.WithOwner("Owner")
                                .HasForeignKey("OwnerId");

                            b1.Navigation("Owner");
                        });

                    b.OwnsOne("Tavernkeep.Core.Entities.Pathfinder.Properties.Speed", "Fly", b1 =>
                        {
                            b1.Property<Guid>("OwnerId")
                                .HasColumnType("TEXT");

                            b1.Property<bool>("Active")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Base")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Type")
                                .HasColumnType("INTEGER");

                            b1.HasKey("OwnerId");

                            b1.ToTable("Characters");

                            b1.ToJson("Fly");

                            b1.WithOwner("Owner")
                                .HasForeignKey("OwnerId");

                            b1.Navigation("Owner");
                        });

                    b.OwnsOne("Tavernkeep.Core.Entities.Pathfinder.Properties.SavingThrow", "Fortitude", b1 =>
                        {
                            b1.Property<Guid>("OwnerId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("BaseAbility")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Proficiency")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Type")
                                .HasColumnType("INTEGER");

                            b1.HasKey("OwnerId");

                            b1.ToTable("Characters");

                            b1.ToJson("Fortitude");

                            b1.WithOwner("Owner")
                                .HasForeignKey("OwnerId");

                            b1.Navigation("Owner");
                        });

                    b.OwnsOne("Tavernkeep.Core.Entities.Pathfinder.Properties.Ability", "Intelligence", b1 =>
                        {
                            b1.Property<Guid>("OwnerId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("Score")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Type")
                                .HasColumnType("INTEGER");

                            b1.HasKey("OwnerId");

                            b1.ToTable("Characters");

                            b1.ToJson("Intelligence");

                            b1.WithOwner("Owner")
                                .HasForeignKey("OwnerId");

                            b1.Navigation("Owner");
                        });

                    b.OwnsOne("Tavernkeep.Core.Entities.Pathfinder.Properties.Skill", "Intimidation", b1 =>
                        {
                            b1.Property<Guid>("OwnerId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("BaseAbility")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Proficiency")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Type")
                                .HasColumnType("INTEGER");

                            b1.HasKey("OwnerId");

                            b1.ToTable("Characters");

                            b1.ToJson("Intimidation");

                            b1.WithOwner("Owner")
                                .HasForeignKey("OwnerId");

                            b1.Navigation("Owner");
                        });

                    b.OwnsOne("Tavernkeep.Core.Entities.Pathfinder.Properties.Skill", "Medicine", b1 =>
                        {
                            b1.Property<Guid>("OwnerId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("BaseAbility")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Proficiency")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Type")
                                .HasColumnType("INTEGER");

                            b1.HasKey("OwnerId");

                            b1.ToTable("Characters");

                            b1.ToJson("Medicine");

                            b1.WithOwner("Owner")
                                .HasForeignKey("OwnerId");

                            b1.Navigation("Owner");
                        });

                    b.OwnsOne("Tavernkeep.Core.Entities.Pathfinder.Properties.Skill", "Nature", b1 =>
                        {
                            b1.Property<Guid>("OwnerId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("BaseAbility")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Proficiency")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Type")
                                .HasColumnType("INTEGER");

                            b1.HasKey("OwnerId");

                            b1.ToTable("Characters");

                            b1.ToJson("Nature");

                            b1.WithOwner("Owner")
                                .HasForeignKey("OwnerId");

                            b1.Navigation("Owner");
                        });

                    b.OwnsOne("Tavernkeep.Core.Entities.Pathfinder.Properties.Skill", "Occultism", b1 =>
                        {
                            b1.Property<Guid>("OwnerId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("BaseAbility")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Proficiency")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Type")
                                .HasColumnType("INTEGER");

                            b1.HasKey("OwnerId");

                            b1.ToTable("Characters");

                            b1.ToJson("Occultism");

                            b1.WithOwner("Owner")
                                .HasForeignKey("OwnerId");

                            b1.Navigation("Owner");
                        });

                    b.OwnsOne("Tavernkeep.Core.Entities.Pathfinder.Properties.Skill", "Performance", b1 =>
                        {
                            b1.Property<Guid>("OwnerId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("BaseAbility")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Proficiency")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Type")
                                .HasColumnType("INTEGER");

                            b1.HasKey("OwnerId");

                            b1.ToTable("Characters");

                            b1.ToJson("Performance");

                            b1.WithOwner("Owner")
                                .HasForeignKey("OwnerId");

                            b1.Navigation("Owner");
                        });

                    b.OwnsOne("Tavernkeep.Core.Entities.Pathfinder.Properties.SavingThrow", "Reflex", b1 =>
                        {
                            b1.Property<Guid>("OwnerId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("BaseAbility")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Proficiency")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Type")
                                .HasColumnType("INTEGER");

                            b1.HasKey("OwnerId");

                            b1.ToTable("Characters");

                            b1.ToJson("Reflex");

                            b1.WithOwner("Owner")
                                .HasForeignKey("OwnerId");

                            b1.Navigation("Owner");
                        });

                    b.OwnsOne("Tavernkeep.Core.Entities.Pathfinder.Properties.Skill", "Religion", b1 =>
                        {
                            b1.Property<Guid>("OwnerId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("BaseAbility")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Proficiency")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Type")
                                .HasColumnType("INTEGER");

                            b1.HasKey("OwnerId");

                            b1.ToTable("Characters");

                            b1.ToJson("Religion");

                            b1.WithOwner("Owner")
                                .HasForeignKey("OwnerId");

                            b1.Navigation("Owner");
                        });

                    b.OwnsOne("Tavernkeep.Core.Entities.Pathfinder.Properties.Skill", "Society", b1 =>
                        {
                            b1.Property<Guid>("OwnerId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("BaseAbility")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Proficiency")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Type")
                                .HasColumnType("INTEGER");

                            b1.HasKey("OwnerId");

                            b1.ToTable("Characters");

                            b1.ToJson("Society");

                            b1.WithOwner("Owner")
                                .HasForeignKey("OwnerId");

                            b1.Navigation("Owner");
                        });

                    b.OwnsOne("Tavernkeep.Core.Entities.Pathfinder.Properties.Skill", "Stealth", b1 =>
                        {
                            b1.Property<Guid>("OwnerId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("BaseAbility")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Proficiency")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Type")
                                .HasColumnType("INTEGER");

                            b1.HasKey("OwnerId");

                            b1.ToTable("Characters");

                            b1.ToJson("Stealth");

                            b1.WithOwner("Owner")
                                .HasForeignKey("OwnerId");

                            b1.Navigation("Owner");
                        });

                    b.OwnsOne("Tavernkeep.Core.Entities.Pathfinder.Properties.Ability", "Strength", b1 =>
                        {
                            b1.Property<Guid>("OwnerId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("Score")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Type")
                                .HasColumnType("INTEGER");

                            b1.HasKey("OwnerId");

                            b1.ToTable("Characters");

                            b1.ToJson("Strength");

                            b1.WithOwner("Owner")
                                .HasForeignKey("OwnerId");

                            b1.Navigation("Owner");
                        });

                    b.OwnsOne("Tavernkeep.Core.Entities.Pathfinder.Properties.Skill", "Survival", b1 =>
                        {
                            b1.Property<Guid>("OwnerId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("BaseAbility")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Proficiency")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Type")
                                .HasColumnType("INTEGER");

                            b1.HasKey("OwnerId");

                            b1.ToTable("Characters");

                            b1.ToJson("Survival");

                            b1.WithOwner("Owner")
                                .HasForeignKey("OwnerId");

                            b1.Navigation("Owner");
                        });

                    b.OwnsOne("Tavernkeep.Core.Entities.Pathfinder.Properties.Speed", "Swim", b1 =>
                        {
                            b1.Property<Guid>("OwnerId")
                                .HasColumnType("TEXT");

                            b1.Property<bool>("Active")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Base")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Type")
                                .HasColumnType("INTEGER");

                            b1.HasKey("OwnerId");

                            b1.ToTable("Characters");

                            b1.ToJson("Swim");

                            b1.WithOwner("Owner")
                                .HasForeignKey("OwnerId");

                            b1.Navigation("Owner");
                        });

                    b.OwnsOne("Tavernkeep.Core.Entities.Pathfinder.Properties.Skill", "Thievery", b1 =>
                        {
                            b1.Property<Guid>("OwnerId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("BaseAbility")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Proficiency")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Type")
                                .HasColumnType("INTEGER");

                            b1.HasKey("OwnerId");

                            b1.ToTable("Characters");

                            b1.ToJson("Thievery");

                            b1.WithOwner("Owner")
                                .HasForeignKey("OwnerId");

                            b1.Navigation("Owner");
                        });

                    b.OwnsOne("Tavernkeep.Core.Entities.Pathfinder.Properties.Speed", "Walk", b1 =>
                        {
                            b1.Property<Guid>("OwnerId")
                                .HasColumnType("TEXT");

                            b1.Property<bool>("Active")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Base")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Type")
                                .HasColumnType("INTEGER");

                            b1.HasKey("OwnerId");

                            b1.ToTable("Characters");

                            b1.ToJson("Walk");

                            b1.WithOwner("Owner")
                                .HasForeignKey("OwnerId");

                            b1.Navigation("Owner");
                        });

                    b.OwnsOne("Tavernkeep.Core.Entities.Pathfinder.Properties.SavingThrow", "Will", b1 =>
                        {
                            b1.Property<Guid>("OwnerId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("BaseAbility")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Proficiency")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Type")
                                .HasColumnType("INTEGER");

                            b1.HasKey("OwnerId");

                            b1.ToTable("Characters");

                            b1.ToJson("Will");

                            b1.WithOwner("Owner")
                                .HasForeignKey("OwnerId");

                            b1.Navigation("Owner");
                        });

                    b.OwnsOne("Tavernkeep.Core.Entities.Pathfinder.Properties.Ability", "Wisdom", b1 =>
                        {
                            b1.Property<Guid>("OwnerId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("Score")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Type")
                                .HasColumnType("INTEGER");

                            b1.HasKey("OwnerId");

                            b1.ToTable("Characters");

                            b1.ToJson("Wisdom");

                            b1.WithOwner("Owner")
                                .HasForeignKey("OwnerId");

                            b1.Navigation("Owner");
                        });

                    b.OwnsOne("Tavernkeep.Core.Entities.Pathfinder.Properties.Armor", "Armor", b1 =>
                        {
                            b1.Property<Guid>("OwnerId")
                                .HasColumnType("TEXT");

                            b1.HasKey("OwnerId");

                            b1.ToTable("Characters");

                            b1.ToJson("Armor");

                            b1.WithOwner("Owner")
                                .HasForeignKey("OwnerId");

                            b1.OwnsOne("Tavernkeep.Core.Contracts.Structures.EquippedArmor", "Equipped", b2 =>
                                {
                                    b2.Property<Guid>("ArmorOwnerId")
                                        .HasColumnType("TEXT");

                                    b2.Property<int>("Bonus")
                                        .HasColumnType("INTEGER");

                                    b2.Property<int>("DexterityCap")
                                        .HasColumnType("INTEGER");

                                    b2.Property<bool>("HasDexterityCap")
                                        .HasColumnType("INTEGER");

                                    b2.Property<int>("Type")
                                        .HasColumnType("INTEGER");

                                    b2.HasKey("ArmorOwnerId");

                                    b2.ToTable("Characters");

                                    b2.WithOwner()
                                        .HasForeignKey("ArmorOwnerId");
                                });

                            b1.OwnsOne("Tavernkeep.Core.Entities.Pathfinder.Properties.ArmorProficiencies", "Proficiencies", b2 =>
                                {
                                    b2.Property<Guid>("ArmorOwnerId")
                                        .HasColumnType("TEXT");

                                    b2.Property<int>("Heavy")
                                        .HasColumnType("INTEGER");

                                    b2.Property<int>("Light")
                                        .HasColumnType("INTEGER");

                                    b2.Property<int>("Medium")
                                        .HasColumnType("INTEGER");

                                    b2.Property<int>("Unarmored")
                                        .HasColumnType("INTEGER");

                                    b2.HasKey("ArmorOwnerId");

                                    b2.ToTable("Characters");

                                    b2.WithOwner()
                                        .HasForeignKey("ArmorOwnerId");
                                });

                            b1.Navigation("Equipped")
                                .IsRequired();

                            b1.Navigation("Owner");

                            b1.Navigation("Proficiencies")
                                .IsRequired();
                        });

                    b.OwnsOne("Tavernkeep.Core.Entities.Pathfinder.Properties.Health", "Health", b1 =>
                        {
                            b1.Property<Guid>("OwnerId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("Current")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Max")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Temporary")
                                .HasColumnType("INTEGER");

                            b1.HasKey("OwnerId");

                            b1.ToTable("Characters");

                            b1.ToJson("Health");

                            b1.WithOwner("Owner")
                                .HasForeignKey("OwnerId");

                            b1.Navigation("Owner");
                        });

                    b.OwnsMany("Tavernkeep.Core.Entities.Pathfinder.Properties.Lore", "Lores", b1 =>
                        {
                            b1.Property<Guid>("OwnerId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAddOrUpdate()
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Proficiency")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Topic")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.HasKey("OwnerId", "__synthesizedOrdinal");

                            b1.ToTable("Characters");

                            b1.ToJson("Lores");

                            b1.WithOwner("Owner")
                                .HasForeignKey("OwnerId");

                            b1.Navigation("Owner");
                        });

                    b.OwnsOne("Tavernkeep.Core.Entities.Pathfinder.Properties.Perception", "Perception", b1 =>
                        {
                            b1.Property<Guid>("OwnerId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("Proficiency")
                                .HasColumnType("INTEGER");

                            b1.HasKey("OwnerId");

                            b1.ToTable("Characters");

                            b1.ToJson("Perception");

                            b1.WithOwner("Owner")
                                .HasForeignKey("OwnerId");

                            b1.Navigation("Owner");
                        });

                    b.Navigation("Acrobatics")
                        .IsRequired();

                    b.Navigation("Arcana")
                        .IsRequired();

                    b.Navigation("Armor")
                        .IsRequired();

                    b.Navigation("Athletics")
                        .IsRequired();

                    b.Navigation("Burrow")
                        .IsRequired();

                    b.Navigation("Charisma")
                        .IsRequired();

                    b.Navigation("Climb")
                        .IsRequired();

                    b.Navigation("Conditions");

                    b.Navigation("Constitution")
                        .IsRequired();

                    b.Navigation("Crafting")
                        .IsRequired();

                    b.Navigation("Deception")
                        .IsRequired();

                    b.Navigation("Dexterity")
                        .IsRequired();

                    b.Navigation("Diplomacy")
                        .IsRequired();

                    b.Navigation("Fly")
                        .IsRequired();

                    b.Navigation("Fortitude")
                        .IsRequired();

                    b.Navigation("Health")
                        .IsRequired();

                    b.Navigation("Intelligence")
                        .IsRequired();

                    b.Navigation("Intimidation")
                        .IsRequired();

                    b.Navigation("Lores");

                    b.Navigation("Medicine")
                        .IsRequired();

                    b.Navigation("Nature")
                        .IsRequired();

                    b.Navigation("Occultism")
                        .IsRequired();

                    b.Navigation("Owner");

                    b.Navigation("Perception")
                        .IsRequired();

                    b.Navigation("Performance")
                        .IsRequired();

                    b.Navigation("Reflex")
                        .IsRequired();

                    b.Navigation("Religion")
                        .IsRequired();

                    b.Navigation("Society")
                        .IsRequired();

                    b.Navigation("Stealth")
                        .IsRequired();

                    b.Navigation("Strength")
                        .IsRequired();

                    b.Navigation("Survival")
                        .IsRequired();

                    b.Navigation("Swim")
                        .IsRequired();

                    b.Navigation("Thievery")
                        .IsRequired();

                    b.Navigation("Walk")
                        .IsRequired();

                    b.Navigation("Will")
                        .IsRequired();

                    b.Navigation("Wisdom")
                        .IsRequired();
                });

            modelBuilder.Entity("Tavernkeep.Core.Entities.Pathfinder.Conditions.ConditionTemplate", b =>
                {
                    b.OwnsMany("Tavernkeep.Core.Entities.Pathfinder.Modifiers.Modifier", "Modifiers", b1 =>
                        {
                            b1.Property<string>("ConditionTemplateName")
                                .HasColumnType("TEXT");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAddOrUpdate()
                                .HasColumnType("INTEGER");

                            b1.Property<bool>("IsBonus")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Scaling")
                                .HasColumnType("INTEGER");

                            b1.PrimitiveCollection<string>("Targets")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<int>("Type")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Value")
                                .HasColumnType("INTEGER");

                            b1.HasKey("ConditionTemplateName", "__synthesizedOrdinal");

                            b1.ToTable("Conditions");

                            b1.ToJson("Modifiers");

                            b1.WithOwner()
                                .HasForeignKey("ConditionTemplateName");
                        });

                    b.OwnsMany("Tavernkeep.Core.Entities.Pathfinder.Conditions.Condition", "Related", b1 =>
                        {
                            b1.Property<string>("ConditionTemplateName")
                                .HasColumnType("TEXT");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAddOrUpdate()
                                .HasColumnType("INTEGER");

                            b1.Property<bool>("HasLevels")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Level")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.HasKey("ConditionTemplateName", "__synthesizedOrdinal");

                            b1.ToTable("Conditions");

                            b1.ToJson("Related");

                            b1.WithOwner()
                                .HasForeignKey("ConditionTemplateName");

                            b1.OwnsMany("Tavernkeep.Core.Entities.Pathfinder.Modifiers.Modifier", "Modifiers", b2 =>
                                {
                                    b2.Property<string>("ConditionTemplateName")
                                        .HasColumnType("TEXT");

                                    b2.Property<int>("Condition__synthesizedOrdinal")
                                        .HasColumnType("INTEGER");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAddOrUpdate()
                                        .HasColumnType("INTEGER");

                                    b2.Property<bool>("IsBonus")
                                        .HasColumnType("INTEGER");

                                    b2.Property<int>("Scaling")
                                        .HasColumnType("INTEGER");

                                    b2.PrimitiveCollection<string>("Targets")
                                        .IsRequired()
                                        .HasColumnType("TEXT");

                                    b2.Property<int>("Type")
                                        .HasColumnType("INTEGER");

                                    b2.Property<int>("Value")
                                        .HasColumnType("INTEGER");

                                    b2.HasKey("ConditionTemplateName", "Condition__synthesizedOrdinal", "__synthesizedOrdinal");

                                    b2.ToTable("Conditions");

                                    b2.ToJson("Modifiers");

                                    b2.WithOwner()
                                        .HasForeignKey("ConditionTemplateName", "Condition__synthesizedOrdinal");
                                });

                            b1.Navigation("Modifiers");
                        });

                    b.Navigation("Modifiers");

                    b.Navigation("Related");
                });

            modelBuilder.Entity("Tavernkeep.Core.Entities.User", b =>
                {
                    b.HasOne("Tavernkeep.Core.Entities.Pathfinder.Character", "ActiveCharacter")
                        .WithMany()
                        .HasForeignKey("ActiveCharacterId");

                    b.Navigation("ActiveCharacter");
                });

            modelBuilder.Entity("Tavernkeep.Core.Entities.Messages.RollMessage", b =>
                {
                    b.OwnsOne("Tavernkeep.Core.Entities.Rolls.RollResult", "Result", b1 =>
                        {
                            b1.Property<Guid>("RollMessageId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("Modifier")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Value")
                                .HasColumnType("INTEGER");

                            b1.HasKey("RollMessageId");

                            b1.ToTable("Messages");

                            b1.ToJson("Result");

                            b1.WithOwner()
                                .HasForeignKey("RollMessageId");

                            b1.OwnsMany("Tavernkeep.Core.Entities.Rolls.ThrowResult", "Results", b2 =>
                                {
                                    b2.Property<Guid>("RollResultRollMessageId")
                                        .HasColumnType("TEXT");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAddOrUpdate()
                                        .HasColumnType("INTEGER");

                                    b2.Property<string>("Type")
                                        .IsRequired()
                                        .HasColumnType("TEXT");

                                    b2.Property<int>("Value")
                                        .HasColumnType("INTEGER");

                                    b2.HasKey("RollResultRollMessageId", "__synthesizedOrdinal");

                                    b2.ToTable("Messages");

                                    b2.WithOwner()
                                        .HasForeignKey("RollResultRollMessageId");
                                });

                            b1.Navigation("Results");
                        });

                    b.Navigation("Result")
                        .IsRequired();
                });

            modelBuilder.Entity("Tavernkeep.Core.Entities.Messages.TextMessage", b =>
                {
                    b.HasOne("Tavernkeep.Core.Entities.User", "Recipient")
                        .WithMany()
                        .HasForeignKey("RecipientId");

                    b.Navigation("Recipient");
                });

            modelBuilder.Entity("Tavernkeep.Core.Entities.Messages.SavingThrowRollMessage", b =>
                {
                    b.OwnsOne("Tavernkeep.Core.Entities.Snapshots.SavingThrowSnapshot", "SavingThrow", b1 =>
                        {
                            b1.Property<Guid>("SavingThrowRollMessageId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("Bonus")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Proficiency")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Type")
                                .HasColumnType("INTEGER");

                            b1.HasKey("SavingThrowRollMessageId");

                            b1.ToTable("Messages");

                            b1.ToJson("SavingThrow");

                            b1.WithOwner()
                                .HasForeignKey("SavingThrowRollMessageId");
                        });

                    b.Navigation("SavingThrow")
                        .IsRequired();
                });

            modelBuilder.Entity("Tavernkeep.Core.Entities.Messages.SkillRollMessage", b =>
                {
                    b.OwnsOne("Tavernkeep.Core.Entities.Snapshots.SkillSnapshot", "Skill", b1 =>
                        {
                            b1.Property<Guid>("SkillRollMessageId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("Bonus")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Proficiency")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Type")
                                .HasColumnType("INTEGER");

                            b1.HasKey("SkillRollMessageId");

                            b1.ToTable("Messages");

                            b1.ToJson("Skill");

                            b1.WithOwner()
                                .HasForeignKey("SkillRollMessageId");
                        });

                    b.Navigation("Skill")
                        .IsRequired();
                });

            modelBuilder.Entity("Tavernkeep.Core.Entities.User", b =>
                {
                    b.Navigation("Characters");
                });
#pragma warning restore 612, 618
        }
    }
}
