using NCalc;
using Tavernkeep.Domain.Contracts.Structures;
using Tavernkeep.Domain.Entities.Encounters.Participants;
using Tavernkeep.Domain.Entities.Library.Creatures;

namespace Tavernkeep.Domain.Entities.Pathfinder.Conditions;

public class CreatureConditionRecord : ConditionRecord
{
	/* We must to explicitly declare CreatureEncounterParticipant as a property in CreatureConditionRecord.
	 * Otherwise shadow key that will be generated by EF will behave incorrectly
	 * and instead of deleting the CreatureConditionRecord from DB it will simply set 
	 * CreatureEncounterParticipantId key to null and leave the record inside DB
	 * leading to equivalent of a memory leak.
	 */
	public required CreatureEncounterParticipant Participant { get; set; }
	public required Creature Creature { get; set; }

	#region Methods

	protected override ICollection<int> Calculate(IEnumerable<Modifier> modifiers)
	{
		return modifiers.Select(x =>
		{
			var expression = new Expression(x.Formula);
			expression.Parameters["target_level"] = Creature.Level;
			expression.Parameters["condition_level"] = Level;

			return Convert.ToInt32(expression.Evaluate());
		}).ToList();
	}

	#endregion
}
